# Generated by Django 4.2.7 on 2023-12-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0004_alter_boardmodel_sns_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmodel',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
